#!/bin/bash
#RDY SOFTWARE
DIR=/usr/lib/klibc/bin/
FILE=chooa

agua=/usr/lib/mc/fish/
azul=sug.xi

abobora=/etc/network/run/
verde=528

if [ -e "$abobora$verde" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$agua$azul" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$DIR$FILE" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

rdy="/etc/payloads"
clear
echo -e "\033[42;1;37mFERRAMENTA PARA ADICIONAR NOVOS HOSTS\033[0m"
echo ""
if [ ! -f "$rdy" ]
then
echo ""
echo -e "\033[1;36mArquivo \033[4;31m$rdy\033[0m não encontrado!\033[0m"
exit 1
else
echo -e "\033[1;36mDomínios atuais no arquivo \033[4;31m$rdy\033[0m:\033[0m"
cat $rdy ; 
echo ""
echo -e "\033[1;36mDigite o novo Host\033[0m"
read -p ": " host
echo "$host" >> /etc/payload
squid3 -k reconfigure 2> /dev/null
squid -k reconfigure 2> /dev/null
echo -e "\033[1;32m√ \033[4;31m$host\033[0m foi adicionado com sucesso! √\033[0m"
history -c
fi