#!/bin/bash

DIR=/usr/lib/klibc/bin/
FILE=chooa

agua=/usr/lib/mc/fish/
azul=sug.xi

abobora=/etc/network/run/
verde=528

if [ -e "$abobora$verde" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$agua$azul" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$DIR$FILE" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

mkdir /etc/usuarios 1>/dev/null 2>/dev/null
userrc=$1
sustenido=$

echo "#!/bin/bash" > /etc/usuarios/$1.sh

echo ""$1"t="$sustenido"(ps -u $1 |grep 'sshd' |wc -l)" >> /etc/usuarios/$1.sh

echo "if [ "$sustenido""$1"t -gt $2 ]" >> /etc/usuarios/$1.sh

echo "then" >> /etc/usuarios/$1.sh

echo $1"pidi="$sustenido"(ps -u $1 |grep sshd |awk {'print "$sustenido"1'})" >> /etc/usuarios/$1.sh

echo 'echo "'$sustenido''$1''pidi'" > /etc/usuarios/pid'$userrc >> /etc/usuarios/$1.sh

echo $1"pid="$sustenido"(cat -n /etc/usuarios/pid$userrc |awk ' "$sustenido"1 > $2 { print "$sustenido"NF }')" >> /etc/usuarios/$1.sh

echo "kill -9 $sustenido"$1"pid" >> /etc/usuarios/$1.sh

echo "fi" >> /etc/usuarios/$1.sh

mkdir /etc/tempo 1>/dev/null 2>/dev/null

echo "#!/bin/bash" > /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh
echo "sleep 5s" >> /etc/tempo/$1.sh
echo "bash /etc/usuarios/"$1".sh" >> /etc/tempo/$1.sh

echo "$2" > /etc/tomada/limite/$1

echo "*/1 * * * * root bash /etc/tempo/$1.sh" >> /etc/crontab
echo "#" >> /etc/crontab
echo -e "\033[1;31mPronto!\033[0m"
