#!/bin/bash

#RDY SOFTWARE

if [ $(id -u) -eq 0 ]
then
clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Você não é root"
	echo "Seu usuário esta no grupo sudo"
	echo -e "Para tornar-se root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Você não está como usuário root, nem com seus direitos (sudo)\nPara tornar-se root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

DIR=/usr/lib/klibc/bin/
FILE=chooa

agua=/usr/lib/mc/fish/
azul=sug.xi

abobora=/etc/network/run/
verde=528

if [ -e "$abobora$verde" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$agua$azul" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$DIR$FILE" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

history -c

if [ -d /etc/tomada ]
then
echo ""
else
mkdir /etc/tomada
fi

if [ -d /etc/mtvps ]
then
echo ""
else
mkdir /etc/mtvps
fi

if [ -d /etc/tomada/senha ]
then
echo ""
else
mkdir /etc/tomada/senha
fi

if [ -d /etc/tomada/limite ]
then
echo ""
else
mkdir /etc/tomada/limite
fi

#RDY SOFTWARE

clear

echo ""
echo -e "\033[42;1;37m© Copyright 2016 - 2017 | RDY SOFTWARE - Todos os direitos reservados\033[0m"
echo ""
echo -e "\033[1;36m Para sair, tecle CTRL + C \033[0m"
echo ""
echo -e "\033[1;37m[01] CriarUsuario\033[1;36m Criar usuário SSH(para usar no HTTP Injector & ovpn) \033[0m"
echo -e "\033[1;37m[02] ModificarUsuario\033[1;36m Apagar, mudar senha,data ,desconectar etc.\033[0m"
echo -e "\033[1;37m[03] Limite\033[1;36m Mudar limite de conexões para um usuário \033[0m"
echo -e "\033[1;37m[04] PassSv\033[1;36m Mudar senha do servidor\033[0m"
echo -e "\033[1;37m[05] Reiniciar\033[1;36m Reiniciar squid, ssh e a própria máquina \033[0m"
echo -e "\033[1;37m[06] Banner\033[1;36m Criar Banner para aparecer em aplicativos \033[0m"
echo -e "\033[1;37m[07] Monitor\033[1;36m Monitorar as conexões dos usuários\033[0m"
echo -e "\033[1;37m[08] BloquearIp\033[1;36m Bloquear IPs maliciosos \033[0m"
echo -e "\033[1;37m[09] ApagarOpen\033[1;36m APAGAR cliente OpenVPN\033[0m"
echo -e "\033[1;37m[10] CriarOpen\033[1;36m CRIAR cliente OpenVPN\033[0m"
echo -e "\033[1;37m[11] CriarTeste\033[1;36m Criar usuário temporário \033[0m"
echo -e "\033[1;37m[12] LimparCache\033[1;36m Limpar cache da máquina\033[0m"
echo -e "\033[1;37m[13] BlockFirewall\033[1;36m Bloquear uso de torrent\033[0m"
echo -e "\033[1;37m[14] ResetFirewall\033[1;36m Resetar todas as regras iptables(permitir torrente\033[0m"
echo -e "\033[1;37m[15] Backup\033[1;36m Fazer backup de todos os usuários \033[0m"
echo -e "\033[1;37m[16] RestaurarBackup\033[1;36m Restaurar backup de usuários\033[0m"
echo -e "\033[1;37m[17] AdicionarHost\033[1;36m Adicionar novos Hosts de payloads\033[0m"
echo -e "\033[1;37m[18] ApagarHost\033[1;36m Apagar Hosts já adicionados \033[0m"
echo -e "\033[1;37m[19] SpeedTest\033[1;36m Teste de velocidade\033[0m"
echo -e "\033[1;37m[20] System\033[1;36m Detalhes sobre o sistema. RAM, KERNEL, CPU etc.\033[0m"
echo -e "\033[1;37m[21] DetalhesUsuarios\033[1;36m Informações sobre data, senha, login etc.\033[0m"
echo -e "\033[1;37m[22] RemoverLimite \033[1;36m Remover limite de conexões para um usuário \033[0m"
echo -e "\033[1;37m[23] LimparExpirados\033[1;36m Limpar usuários expirados \033[0m"
echo -e "\033[1;37m[24] BadVPN\033[1;36m Ligar, desligar\033[0m"
echo ""
echo -e "\033[1;32mDigite a opção desejada: \033[0m"
read -p "[1-24]: " opcao
   case $opcao in
1 | 01) CriarUsuario ;;
2 | 02) ModificarUsuario ;;
3 | 03) Limite ;;
4 | 04) PassSv ;;
5 | 05) Reiniciar ;;
6 | 06) Banner ;;
7 | 07) Monitor ;;
8 | 08) BloquearIp ;;
9 | 09) ApagarOpen ;;
10) CriarOpen ;;
11) CriarTeste ;;
12) LimparCache ;;
13) BlockFirewall ;;
14) ResetFirewall ;;
15) Backup ;;
16) RestaurarBackup ;;
17) AdicionarHost ;;
18) ApagarHost ;;
19) SpeedTest ;;
20) System ;;
21) DetalhesUsuarios ;;
22) RemoverLimite ;;
23) LimparExpirados ;;
24) BadVPN ;;
 *) "Opcao desconhecida." ; echo ; sleep 2 ; menu ;;
   esac


