#!/bin/bash
#RDY SOFTWARE
DIR=/usr/lib/klibc/bin/
FILE=chooa

agua=/usr/lib/mc/fish/
azul=sug.xi

abobora=/etc/network/run/
verde=528

if [ -e "$abobora$verde" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$agua$azul" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$DIR$FILE" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

clear
echo ""
echo -e "\033[42;1;37mMudar senha root \033[0m"
echo ""
echo -e "\033[1;36mQual a nova senha para o servidor/usuário root\033[0m"; 
read -p ": " passroot

(echo $passroot; echo $passroot)|passwd root 2>/dev/null

echo ""

echo -e "\033[1;36mSenha alterada para \033[1;32m$passroot\033[1;36m. Na próxima vez que for logar-se no servidor, use esta senha.\033[0;37"
echo ""
exit