#!/bin/bash

#RDY SOFTWARE
clear

rdy="/root/teste.txt"
echo ""
echo -e "\033[42;1;37mACESS PASSWORD\033[0m"
if [ ! -f "$rdy" ]
then
echo ""
echo -e "\033[1;36mERROR!! PASSWORD NOT FOUND - CODE 404\033[0m"
exit 1
else
echo ""
echo -e "\033[1;36mType your password: \033[0m"; read -p "" senha
if [[ -z $senha ]]
then
echo ""
echo -e "\033[1;31mYou left the empty space one entered a nonexistent password.\033[0m"
exit 1
else
if [[ `grep -c "^$senha" $rdy` -ne 1 ]]
then
echo ""
echo -e "\033[1;31mInvalid password!\nPlease try again.\n\n\033[1;36mPossible causes for this error:\033[1;37m\nYou have entered the wrong password.\nYour password has expired.\nYou are not registered.\033[1;32m\nIf you do not have a password, send an email to \033[1;37mtomadassh@gmail.com\033[0m and request a password. \033[0m"
echo ""
exit 1
else
#grep -v "^$host" $rdy > /tmp/a && mv /tmp/a $rdy
echo ""
echo -e "\033[1;36m\033[1;32m√ \033[0mValid password!\033[0m"
echo ""
			exit 1
		fi
	fi
fi