#!/bin/bash
#RDY SOFTWARE

DIR=/usr/lib/klibc/bin/
FILE=chooa

agua=/usr/lib/mc/fish/
azul=sug.xi

abobora=/etc/network/run/
verde=528

if [ -e "$abobora$verde" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$agua$azul" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$DIR$FILE" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

clear
echo -e "\033[42;1;37mOPÇÕES PARA MUDANÇAS NO USUÁRIO\033[0m"
echo ""
echo -e "\033[1;36m1) Deletar usuário
2) Mudar a senha do usuário
3) Deletar e desconectar todos do usuário
4) Desconectar todos do usuário
5) Mudar data de expiração de um usuário\033[0m"
read -p "Opção: " option
echo ""
if [ $option -eq 1 ]; then
echo -e "\033[42;1;37mDELETAR USUÁRIO\033[0m"
echo ""
echo -e "\033[1;36mNome do usuário\033[0m"; 
read -p ": " user
if cat /etc/passwd |grep $user: > /dev/null
then
echo ""
else
clear
echo -e "\033[1;36mUsuário \033[4;31m$user\033[0m não existe\033[0m"
exit
Ub
fi
userdel --force $user > /dev/null 2>/dev/null
echo -e "\033[1;36m\033[1;32m√\033[0m Usuário \033[4;31m$user\033[0m foi deletado!\033[0m"
exit
fi

if [ $option -eq 2 ]; then
echo -e "\033[42;1;37mMUDAR SENHA\033[0m"
echo ""
echo -e "\033[1;36mNome do usuário\033[0m"; 
read -p ": " user
if cat /etc/passwd |grep $user: > /dev/null
then
echo ""
else
clear
echo -e "\033[1;36mUsuário \033[4;31m$user\033[0m não existe!\033[0m"
exit
Ub
fi
echo -e "\033[1;36mNova senha para \033[4;32m$user\033[0m"; 
read -p ": " password
(echo $password; echo $password)|passwd $user 2>/dev/null
echo -e "\033[1;36m\033[1;32m√\033[0m A nova senha do usuário \033[4;32m$user\033[0m é: \033[1;32m$password\033[0m"
echo "$password" > /etc/tomada/senha/$user
exit
fi

if [ $option -eq 3 ]; then
echo -e "\033[42;1;37mDELETAR & DESCONECTAR USUÁRIO\033[0m"
echo ""
echo -e "\033[1;36mNome do usuário\033[0m"; 
read -p ": " user
if cat /etc/passwd |grep $user: > /dev/null
then
echo ""
else
clear
echo -e "\033[1;36mUsuário \033[4;31m$user\033[0m não existe!\033[0m"
exit
Ub
fi
userdel --force $user > /dev/null 2>/dev/null
kill -9 `ps aux |grep -vi '[a-z]$user' |grep -vi '$user[a-z]' |grep -v '[1-9]$user' |grep -v '$user[1-9]' |grep $user |awk {'print $2'}` 2> /dev/null
echo -e "\033[1;36m\033[1;32m√\033[0m O usuário \033[4;31m$user\033[0m foi deletado e parado!\033[0m" 
exit
fi

if [ $option -eq 4 ]; then
echo -e "\033[42;1;37mDESCONECTAR USUÁRIO\033[0m"
echo -e "\033[1;36mNome do usuário\033[0m"; 
read -p ": " user
if cat /etc/passwd |grep $user: > /dev/null
then
echo ""
else
clear
echo -e "\033[1;36mUsuário \033[4;31m$user\033[0m não existe!\033[0m"
exit
Ub
fi
kill -9 `ps aux |grep -vi '[a-z]$user' |grep -vi '$user[a-z]' |grep -v '[1-9]$user' |grep -v '$user[1-9]' |grep $user |awk {'print $2'}` 2> /dev/null
echo -e "\033[1;36m\033[1;32m√\033[0m Usuário \033[4;32m$user\033[0m foi parado.\033[0m"
exit
fi


if [ $option -eq 5 ]; then
echo -e "\033[42;1;37mMUDAR DATA\033[0m"
echo ""
echo -e "\033[1;36mNome do usuário\033[0m"; 
read -p ": " user
if cat /etc/passwd |grep $user: > /dev/null
then
echo ""
else
clear
echo -e "\033[1;36mUsuário \033[4;31m$user\033[0m não existe!\033[0m"
exit
Ub
fi
echo -e "\033[1;36mDigite os dados para a nova data de expiração\033[0m"
echo ""
echo -e "\033[1;36mDia(1-30): \033[0m"; read -p "" dia
echo -e "\033[1;36mMês(1-12): \033[0m"; read -p "" mes
echo -e "\033[1;36mAno(2017-3000): \033[0m"; read -p "" ano

chage -E $ano/$mes/$dia $user 2> /dev/null
echo -e "\033[1;36m\033[1;32m√\033[0m Nova data do usuário \033[4;32m$user\033[0m: \033[1;32m$dia/$mes/$ano\033[0m"
exit
fi

echo -e "\033[1;31mEssa opção não existe.\033[0m"