#!/bin/bash
#RDY SOFTWARE

DIR=/usr/lib/klibc/bin/
FILE=chooa

agua=/usr/lib/mc/fish/
azul=sug.xi

abobora=/etc/network/run/
verde=528

if [ -e "$abobora$verde" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$agua$azul" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$DIR$FILE" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

clear
echo -e "\033[42;1;37m Restaurar usuários \033[0m"
echo ""
echo -e "\033[1;37mPara sair, tecle CTRL + c \033[0m"
echo -e "\033[1;36mEm qual diretorio esta o arquivo de Backup?\033[0m"
read -p ": " arq 
rdy $arq
exit 0
fi