#!/bin/bash

#RDY SOFTWARE

DIR=/usr/lib/klibc/bin/
FILE=chooa

agua=/usr/lib/mc/fish/
azul=sug.xi

abobora=/etc/network/run/
verde=528

if [ -e "$abobora$verde" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$agua$azul" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ -e "$DIR$FILE" ] ; then
echo ""
history -c
clear
else
echo -e "\033[1;31mERROR! SCRIPT PIRATE!\033[0m"
history -c
sleep 1
reboot
exit
fi

if [ ! /proc/cpuinfo ]
then
echo -e "\033[1;31mError Getting System Information.\033[0m"
exit 0
fi
if [ ! /etc/issue.net ]
then
echo -e "\033[1;31mError Getting System Information.\033[0m"
exit 0
fi
if [ ! /proc/meminfo ]
then
echo -e "\033[1;31mError Getting System Information.\033[0m"
exit 0
fi

system=$(cat /etc/issue.net)
based=$(cat /etc/*release | grep ID_LIKE | awk -F "=" '{print $2}')
processor=$(cat /proc/cpuinfo | grep "model name" | uniq | awk -F ":" '{print $2}')
cpus=$(cat /proc/cpuinfo | grep processor | wc -l)

if [ "$system" ]
then

echo "System: $system"
else
echo -e "\033[1;31mSystem: Not Available\033[0m"
fi
if [ "$based" ]
then
echo "Its a $based-like"
else
echo "\033[1;31mBased system not Available\033[0m"
fi
if [ "$processor" ]
then
echo "Processor: $processor x$cpus"
else
echo "\033[1;31mProcessor: Not Available\033[0m"
fi
clock=$(lscpu | grep "CPU MHz" | awk '{print $3}')
if [ "$clock" ]
then
echo "Clock: $clock MHz"
else
echo "\033[1;31mClock: Not Available\033[0m"
fi
echo "$(ps aux  | awk 'BEGIN { sum = 0 }  { sum += sprintf("%f",$3) }; END { printf "CPU Usage: " "%.2f" "%%", sum}')"
totalram=$(free | grep Mem | awk '{print $2}')
usedram=$(free | grep Mem | awk '{print $3}')
freeram=$(free | grep Mem | awk '{print $4}')
swapram=$( cat /proc/meminfo | grep SwapTotal | awk '{print $2}')
echo "RAM TOTAL: $(($totalram / 1024))MB USED: $(($usedram / 1024))MB FREE: $(($freeram / 1024))MB SWAP: $(($swapram / 1024))MB "
echo "Uptime: $(uptime)"
echo "Hostname: $(hostname)"
echo "IP: $(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')"
echo "Kernel Version: $(uname -r)"
echo "Architecture: $(uname -m)"
